modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "mtrfranceaddon"
version = "${mod_version}"
displayName = "MTR France Addon"
description = '''This addon is provided to give French Railway content to players through the Minecraft Transit Railway mod by jonafanho.\nCet addon fourni un panel d'éléments du rail français aux joueurs au travers du mod Minecraft Transit Railway par jonafanho.\n\nCreated by the french community - Créer par la communauté française.'''
authors = "Team MTR France"

[[dependencies.mtrfranceaddon]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrfranceaddon]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtrfranceaddon]]
modId = "mtr"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "AFTER"
side = "BOTH"